kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storageclass-zookeeper
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
provisioner: nasplugin.csi.alibabacloud.com
parameters:
  archiveOnDelete: 'false'
  server: '{实例替换}'
  volumeAs: subpath
reclaimPolicy: Delete
mountOptions:
  - 'nolock,tcp,noresvport'
  - vers=3
volumeBindingMode: Immediate