apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
  labels:
    alicloud-pvname: pv-redis
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: redis
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: pv-redis
    volumeAttributes:
      server: "{实例替换}"
      path: "/redis"
  mountOptions:
  - nolock,tcp,noresvport
  - vers=3