apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  labels:
    alicloud-pvname: pv-mongo
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: mongo
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: pv-mongo
    volumeAttributes:
      server: "{实际替换}"
      path: "/mongo"
  mountOptions:
  - nolock,tcp,noresvport
  - vers=3