apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: dev
  labels:
    app: mysql
data:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER_NAME: user
  MYSQL_USER_PASSWORD: user
  MYSQL_DATABASE: test