kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mysql
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mysql
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      alicloud-pvname: pv-mysql