apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    alicloud-pvname: pv-mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: mysql
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: pv-mysql
    volumeAttributes:
      server: "{实际替换}"
      path: "/mysql"
  mountOptions:
  - nolock,tcp,noresvport
  - vers=3